# Generated by Django 5.0 on 2026-01-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
